spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:C:/Users/snehi/OneDrive/Documents/SpringbootDB/module2DB
spring.datasource.username=snehilDB
spring.datasource.password=Snehil123
spring.jpa.hibernate.ddl-auto=update
